import 'package:watsapp_clone/asset.dart';
import 'package:watsapp_clone/widgets/chatCard.widget.dart';

List<Map> chatData = [
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': galaxieonAvatar,
    'subtitle': 'evide do?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': '09/06/2021',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj ck',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': '01/05/2021',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
];
