import 'package:watsapp_clone/asset.dart';
import 'package:watsapp_clone/widgets/chatCard.widget.dart';

List<Map> chatData = [
  {
    'title': 'Galaxieon',
    'avatar': galaxieonAvatar,
    'subtitle': 'surya: Veruthe itataga',
    'time': '12:16 pm',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Muhammad Semeer',
    'avatar': semeerAvatar,
    'subtitle': 'evide do?',
    'time': '7:28 am',
    'messageType': LastMesssageType.Text,
    'isYou': false,
  },
  {
    'title': 'Flutter Devs',
    'avatar': flutterDevAvatar,
    'subtitle': '+91 8720540327: DefaultTabController entha sambavam?',
    'time': '1:55 pm',
    'messageType': LastMesssageType.Text,
    'sendMessageStatus': SendMessage.Read,
    'isYou': false,
  },
  {
    'title': 'JavaScript Developers',
    'avatar': jsdAvatar,
    'subtitle': '+91 5220580527: Lazy loading vach patoole?',
    'time': 'Yesterday',
    'messageType': LastMesssageType.Text,
    'sendMessageStatus': SendMessage.Read,
    'newMessageCount': 2,
    'isYou': false,
  },
  {
    'title': 'Cross Roads Upadates',
    'avatar': crossRoadsAvatr,
    'subtitle': 'React challenge ലെ അവസാന video ഇതാ... ',
    'time': 'Monday',
    'messageType': LastMesssageType.Image,
    'newMessageCount': 1,
    'isYou': false,
  },
  {
    'title': 'Sarthaj Cp',
    'avatar': sarthajAvatar,
    'subtitle': '0:38',
    'time': 'Sunday',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': true,
  },
  {
    'title': 'Elon Musk',
    'avatar': elonMuskAvatar,
    'subtitle': 'tesla company 😢',
    'time': 'Sunday',
    'messageType': LastMesssageType.Text,
    'sendMessageStatus': SendMessage.Read,
    'isYou': false,
  },
  {
    'title': '+91 997084283',
    'avatar': anonymousAvatar1,
    'subtitle': 'Photo',
    'time': '03/04/2021',
    'messageType': LastMesssageType.Image,
    'sendMessageStatus': SendMessage.Read,
    'isYou': false,
  },
  {
    'title': 'Kasim',
    'avatar': kasimAvatar,
    'subtitle': 'Sticker',
    'time': '03/04/2021',
    'messageType': LastMesssageType.Sticker,
    'sendMessageStatus': SendMessage.Read,
    'newMessageCount': 2,
    'isYou': false,
  },
  {
    'title': 'Surya Kirshna',
    'avatar': galaxieonAvatar,
    'subtitle': '0:25',
    'time': '1:55 pm',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': false,
  },
  {
    'title': 'Surya Kirshna',
    'avatar': galaxieonAvatar,
    'subtitle': '0:25',
    'time': '1:55 pm',
    'messageType': LastMesssageType.Voice,
    'sendMessageStatus': SendMessage.Read,
    'isYou': false,
  },
];
